Repository martinmladenov/RankingBot, pull requests merged in 2020-10, with the labels that each got.

#5 Move is_private from user_data to ranks
  commands/toggleprivaterank_command.py
  db_setup.sql
  services/dm_service.py
  services/offers_service.py
  services/ranks_service.py
  services/user_data_service.py
Labels: enhancement

#8 Changed toggleprivaterank
  .gitignore
  commands/help_command.py
  commands/toggleprivaterank_command.py
  services/ranks_service.py
Labels: enhancement, hacktoberfest

#10 Add source column in ranks
  db_setup.sql
  services/ranks_service.py
Labels: enhancement

#15 Add TUD nanobiology programme
  helpers/programmes_helper.py
Labels: enhancement, hacktoberfest

#16 Create command to import data from CSV
  commands/importcsv_command.py
  services/data_import_service.py
Labels: enhancement

#14 Made changes to constant
  constants.py
  services/dm_service.py
  services/offers_service.py
  services/ranks_service.py
  utils/offer_date_util.py
Labels: enhancement, hacktoberfest

#18 Fix private rank status not being set when importing from CSV
  services/data_import_service.py
  services/ranks_service.py
Labels: bug
