Repository martinmladenov/RankingBot, pull requests merged in 2022-04, with the labels that each got.

#86 Add role deletion
  commands/createrolemenu_command.py
  handlers/role_button_handler.py
  helpers/role_helper.py
Labels: enhancement

#88 Use UUID in the file name when generating offer graphs to fix concurrency issues
  .gitignore
  commands/offergraph_command.py
  services/offers_service.py
Labels: bug

#89 Add offer graph branding
  .gitignore
  requirements.txt
  resources/3tu_offers_overlay.png
  resources/development/3tu_offers_overlay.xcf
  services/offers_service.py
Labels: enhancement

#90 Notify users when they have no programme roles
  handlers/role_notification_handler.py
  helpers/role_helper.py
Labels: enhancement

#77 Rename clearrank to deleterank
  commands/clearrank_command.py
  commands/command_migration_notification.py
  commands/setrank_command.py
  services/dm_service.py
Labels: hacktoberfest-accepted

#76 getrank command
  commands/getrank_command.py
  services/user_data_service.py
Labels: hacktoberfest-accepted

#92 Fix data import functionality
  services/data_import_service.py
  utils/offer_date_util.py
Labels: bug
